@baseUrl = http://localhost:3000

### AppControllerGetHello

# @name AppControllerGetHello
GET {{baseUrl}}/

### AppControllerGetExemple

# @name AppControllerGetExemple
GET {{baseUrl}}/exemple

### ConceitosManualControllerGetHome

# @name ConceitosManualControllerGetHome
GET {{baseUrl}}/conceitos-manual

### ConceitosAutomaticoControllerGetHome

# @name ConceitosAutomaticoControllerGetHome
GET {{baseUrl}}/conceitos-automatico

### ConceitosManualControllerGetHomeService

# @name ConceitosManualControllerGetHomeService
GET {{baseUrl}}/conceitos-manual/service

### ConceitosAutomaticoControllerGetHomeService

# @name ConceitosAutomaticoControllerGetHomeService
GET {{baseUrl}}/conceitos-automatico/service